// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.bs.js");
var FizzBuzz = require("../src/FizzBuzz.bs.js");
var TestUtil = require("./TestUtil.bs.js");

var expected_3_5_to_15 = "1\n2\n3 fizz\n4\n5 buzz\n6 fizz\n7\n8\n9 fizz\n10 buzz\n11\n12 fizz\n13\n14\n15 fizz buzz";

var expected_3_5_7_to_21 = "1\n2\n3 fizz\n4\n5 buzz\n6 fizz\n7 sezz\n8\n9 fizz\n10 buzz\n11\n12 fizz\n13\n14 sezz\n15 fizz buzz\n16\n17\n18 fizz\n19\n20 buzz\n21 fizz sezz";

Jest.describe("FizzBuzz", (function (param) {
        TestUtil.test_equal("fizz_buzz_3_5 1~15", FizzBuzz.fizz_buzz_3_5(15), expected_3_5_to_15);
        return TestUtil.test_equal("fizz_buzz_3_5_7 1~21", FizzBuzz.fizz_buzz_sezz(21), expected_3_5_7_to_21);
      }));

exports.expected_3_5_to_15 = expected_3_5_to_15;
exports.expected_3_5_7_to_21 = expected_3_5_7_to_21;
/*  Not a pure module */
