// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.bs.js");

function test_equal(name, actual, expected) {
  return Jest.test(name, (function (param) {
                return Jest.Expect.toEqual(expected, Jest.Expect.expect(actual));
              }));
}

test_equal("test_equal test 128 + 128 = 256", 256, 256);

exports.test_equal = test_equal;
/*  Not a pure module */
