// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Day9 = require("../../src/week2/Day9.bs.js");
var Jest = require("@glennsl/bs-jest/src/jest.bs.js");
var TestUtil = require("../TestUtil.bs.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");

var test_input = "35\n20\n15\n25\n47\n40\n62\n55\n65\n95\n102\n117\n150\n182\n127\n219\n299\n277\n309\n576";

var test_numbers_expected = [
  35,
  20,
  15,
  25,
  47,
  40,
  62,
  55,
  65,
  95,
  102,
  117,
  150,
  182,
  127,
  219,
  299,
  277,
  309,
  576
];

var real_input = Fs.readFileSync("input/Day9.txt", "utf8").trim();

Jest.describe("parseNumbers", (function (param) {
        TestUtil.test_equal("test_input을 넣으면 기대하는 array<int>를 반환한다", Day9.parseNumbers(test_input), test_numbers_expected);
        return TestUtil.test_equal("real_input을 넣으면 반환하는 array의 길이가 1000이다.", Day9.parseNumbers(real_input).length, 1000);
      }));

Jest.describe("find_invalid", (function (param) {
        TestUtil.test_equal("[1...25, 50] 에 (preamble=25)로 실행하면 50을 반환한다.", Day9.find_invalid(25, Belt_Array.range(1, 25).concat([50])), 50);
        TestUtil.test_equal("test_numbers에 (preamble=5)로 실행하면 127을 반환한다", Day9.find_invalid(5, Day9.parseNumbers(test_input)), 127);
        return TestUtil.test_equal("real_numbers에 (preamble=25)로 실행하면 675280050를 반환한다", Day9.find_invalid(25, Day9.parseNumbers(real_input)), 675280050);
      }));

Jest.describe("find_contiguous_set", (function (param) {
        var test_result = Day9.find_contiguous_set(Day9.parseNumbers(test_input), 127);
        TestUtil.test_equal("test_input을 넣고 target=127로 실행하면 [15,25,47,40] 을 반환한다", test_result, [
              15,
              25,
              47,
              40
            ]);
        TestUtil.test_equal("test_input을 넣고 target=127으로 실행하면 최솟값 최댓값의 합은 67 이다.", Day9.min_max_sum(test_result), 62);
        var real_result = Day9.find_contiguous_set(Day9.parseNumbers(real_input), 675280050);
        return TestUtil.test_equal("real_input을 넣고 target=675280050으로 실행하면 최삿값 최댓값의 합은 96081673 이다.", Day9.min_max_sum(real_result), 96081673);
      }));

exports.test_input = test_input;
exports.test_numbers_expected = test_numbers_expected;
exports.real_input = real_input;
/* real_input Not a pure module */
