// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_SetString = require("bs-platform/lib/js/belt_SetString.js");

function get_group_list(input) {
  return input.trim().split("\n\n");
}

var all_alpha_lower = "abcdefghijklmnopqrstuvwxyz";

var valid_answer_set = Belt_SetString.fromArray(all_alpha_lower.split(""));

function count_group_unique(group) {
  return Belt_SetString.size(Belt_SetString.fromArray(group.split("").filter(function (v) {
                      return Belt_SetString.has(valid_answer_set, v);
                    })));
}

function count_every_person(group) {
  return group.split("\n").reduce((function (acc, answer) {
                var answer_set = Belt_SetString.fromArray(answer.split(""));
                return acc.filter(function (v) {
                            return Belt_SetString.has(answer_set, v);
                          });
              }), all_alpha_lower.split("")).length;
}

exports.get_group_list = get_group_list;
exports.all_alpha_lower = all_alpha_lower;
exports.valid_answer_set = valid_answer_set;
exports.count_group_unique = count_group_unique;
exports.count_every_person = count_every_person;
/* valid_answer_set Not a pure module */
