// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

function fizz_buzz_3_5(end) {
  return Belt_Array.range(1, end).map(function (n) {
                var match = n % 3 === 0;
                var match$1 = n % 5 === 0;
                var right = match ? (
                    match$1 ? " fizz buzz" : " fizz"
                  ) : (
                    match$1 ? " buzz" : ""
                  );
                return String(n) + right;
              }).join("\n");
}

function fizz_buzz_sezz(end) {
  return Belt_Array.range(1, end).map(function (n) {
                var right = [
                      [
                        3,
                        "fizz"
                      ],
                      [
                        5,
                        "buzz"
                      ],
                      [
                        7,
                        "sezz"
                      ]
                    ].map(function (param) {
                        if (Caml_int32.mod_(n, param[0]) === 0) {
                          return " " + param[1];
                        } else {
                          return "";
                        }
                      }).join("");
                return String(n) + right;
              }).join("\n");
}

exports.fizz_buzz_3_5 = fizz_buzz_3_5;
exports.fizz_buzz_sezz = fizz_buzz_sezz;
/* No side effect */
