// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function boolean_sum(bool_arr) {
  return bool_arr.reduce((function (acc, v) {
                return acc + (
                        v ? 1 : 0
                      ) | 0;
              }), 0);
}

exports.boolean_sum = boolean_sum;
/* No side effect */
